version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: /home/ubuntu/cci-demo-react
    steps:
      - checkout
      - run: mkdir -p /home/ubuntu/cci-demo-react/artifacts
      - run: npm install
      - run: npm test
